extern uint32_t t_delta_us;
extern bool s_limit_low;
extern bool s_limit_high;
extern bool c_button_start;
extern bool c_button_stop;
extern int32_t s_encoder_position;
extern uint8_t c_bpm;
extern uint8_t c_ie_exhale;
extern uint8_t c_ie_inhale;
extern int32_t s_insp_flow_1;
extern uint8_t c_mode;
extern bool c_cmv_mode;
extern uint32_t c_cmv_volume_goal;
extern uint32_t c_cmv_pressure_goal;
void raise_alarm(void);
void update_ui(uint8_t state, uint8_t mode, int32_t flow, int32_t volume_ml, int32_t pressure, uint8_t bpm_limited, uint8_t ie_inhale, uint8_t ie_exhale, bool cmv_mode, uint32_t cmv_volume_goal, uint32_t cmv_pressure_goal);
void control_motor(int32_t us_per_pulse);
void debug(int32_t encoder, int32_t encoder_low, int32_t encoder_high);
void step(void);